Whats_new/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations

  root "users#index"

  resources :users, only: [ :index, :show,:new, :create, :edit, :update]
  resources :chats, only: [ :index, :show,:new, :create, :edit, :update]
  resources :messages, only: [ :index, :show,:new, :create, :edit, :update]
end

Whats_new/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, :all
    can :create, Message
    can [:update, :destroy], Message, user_id: user.id
  end
end

Whats_new/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Whats_new/app/models/chat.rb
class Chat < ApplicationRecord
    has_many :messages
    belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
    belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'
    validates :sender_id, presence: true
    validates :receiver_id, presence: true
    validate :sender_and_receiver_are_different
    
    scope :for_user, ->(user) {
    where(sender_id: user.id).or(where(receiver_id: user.id))
    }

    def other_participant(current_user)
        sender == current_user ? receiver : sender
    end
    private

    def sender_and_receiver_are_different
        if sender_id == receiver_id
        errors.add(:receiver_id, "must be different from sender")
        end
    end

    
end

Whats_new/app/models/message.rb
class Message < ApplicationRecord
    belongs_to :chat
    belongs_to :user
    validates :body, presence: true
    validate  :user_must_belong_to_chat
private
  def user_must_belong_to_chat
    chat_user_ids = [chat.sender_id, chat.receiver_id]

    unless chat_user_ids.include?(user_id)
      errors.add(
        :user_id,
        "the id must be of a user on the chat (sender o receiver)"
      )
    end
  end
end

Whats_new/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :validatable
  has_many :sent_messages, class_name: 'Message', foreign_key: 'user_id'
  
  has_many :sent_chats, class_name: 'Chat', foreign_key: 'sender_id'
  has_many :received_chats, class_name: 'Chat', foreign_key: 'receiver_id'
  

  validates :email, presence: true, uniqueness: true
end

Whats_new/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

Whats_new/app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chats = Chat.for_user(current_user)
                 .includes(:sender, :receiver)
                 .order(updated_at: :desc)
  end

  def show
    @chat = Chat.find(params[:id])
    authorize! :read, @chat    
    @sender = @chat.sender
    @receiver = @chat.receiver                
    @messages = @chat.messages.order(created_at: :asc)
  end

  def new
    @chat = Chat.new
  end
    
  def create
    @chat = Chat.new(chat_params)
    if @chat.save
      redirect_to chats_path, notice: "Chat created successfully."
    else
      render :new
    end
  end

  def edit
    @chat = Chat.find(params[:id])
  end

  def update
    @chat = Chat.find(params[:id])
    if @chat.update(chat_params)
      redirect_to @chat, notice: "Chat updated successfully."
    else
      render :edit
    end
  end
  

private
def chat_params
  params.require(:chat).permit(:sender_id, :receiver_id)
end

end

Whats_new/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!
    def index
      @messages = Message.all
    end

    def show
      @message = Message.find(params[:id])
      @user = @message.user
      @chat = @message.chat
    end

    def new
      @message = Message.new
    end

    def create
      @message = Message.new(message_params)
      chat = Chat.find(message_params[:chat_id])
      @message.user_id = chat.sender_id
      if @message.save
        redirect_to messages_path, notice: "Message created successfully."
      else
        render :new
      end
    end

    def edit
      @message = Message.find(params[:id])
    end
    def update
    @message = Message.find(params[:id])
    if @message.update(message_params)
      redirect_to @message, notice: "Message updated correctly."
    else
      render :edit
    end
  end
      
    private

    def message_params
      params.require(:message).permit(:chat_id, :user_id, :body)
    end
  end

Whats_new/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user     = User.find(params[:id])
    @s_chats    = @user.sent_chats
    @r_chats    = @user.received_chats
    @messages = @user.sent_messages.order(created_at: :desc)
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "User created successfully"
    else
      render :new
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: "User updated correctly."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
  end

Whats_new/app/helpers/application_helper.rb
module ApplicationHelper
end

Whats_new/app/views/chats/_form.html.erb
<%= form_with model: @chat, local: true do |form| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat.errors.count, "error") %> Cant save the chat:</h2>
      <ul>
        <% @chat.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sender_id, "Sender" %><br>
    <%= form.select :sender_id,
          User.all.map { |user|
            ["#{user.first_name} #{user.last_name}", user.id]
          },
          { prompt: "Select a user" } %>
  </div>

  <div class="field">
    <%= form.label :receiver_id, "Receiver" %><br>
    <%= form.select :receiver_id,
          User.all.map { |user|
            ["#{user.first_name} #{user.last_name}", user.id]
          },
          { prompt: "Select a user" } %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

Whats_new/app/views/chats/edit.html.erb
<h1>Edit Chat</h1>
<%= render 'form', chat: @chat %>
<%= link_to 'Back', chats_path %>

Whats_new/app/views/chats/index.html.erb
<h1>Chats</h1>

<%= link_to 'Add new chat', new_chat_path %>

<ul>
  <% @chats.each do |chat| %>
    <li>
      Chat with: <%= chat.other_participant(current_user).first_name %><br>

      <%= link_to 'Show', chat_path(chat) %> |
      <%= link_to 'Edit', edit_chat_path(chat) %>
    </li>
  <% end %>
</ul>

Whats_new/app/views/chats/new.html.erb
<h1>New Chat</h1>
<%= render 'form', chat: @chat %>
<%= link_to 'Back', chats_path %>

Whats_new/app/views/chats/show.html.erb
<h1>chat Details</h1>

<p><strong>Users id:</strong> <%= @chat.sender_id %></p>
<p><strong>Receiver id:</strong> <%= @chat.receiver_id%></p>
<p><strong>Created at:</strong> <%= @chat.created_at %></p>
<p><strong>Updated at:</strong> <%= @chat.updated_at %></p>


<%= link_to 'Back', chats_path %>
<%= link_to 'Edit', edit_chat_path(@chat) %>

<h2>Users of the chat</h2>

<%= link_to("User #{@sender.id}", user_path(@sender)) %>
 and 
 <%= link_to("User #{@receiver.id}", user_path(@receiver)) %>



<h2>Messages</h2>
<% if @messages.any? %>
  <ul>
    <% @messages.each do |message| %>
      <li>
      Message of User<%= message.user_id %>: <%= message.body %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p><em>No messages in this chat.</em></p>
<% end %>

Whats_new/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Whats New" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>


    
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

Whats_new/app/views/messages/_form.html.erb
<%= form_with model: @message, local: true do |form| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> Cant save the message:</h2>
      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :chat_id, "Chat" %><br>
    <%= form.select :chat_id,
          Chat.all.map { |chat|
            ["#{chat.sender.first_name} & #{chat.receiver.id}", chat.id]
          },
          { prompt: "Select a chat" } %>
  </div>

  <div class="field">
    <%= form.label :user_id, "User" %><br>
    <%= form.select :user_id,
          User.all.map { |u|
            ["#{u.first_name}", u.id]
          },
          { prompt: "Select an User" } %>
  </div>

  <div class="field">
    <%= form.label :body, "Message" %><br>
    <%= form.text_area :body, rows: 5 %>
  </div>

  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>

Whats_new/app/views/messages/edit.html.erb
<h1>Edit Message</h1>
<%= render 'form', message: @message %>
<%= link_to 'Back', message_path(@message) %>

Whats_new/app/views/messages/index.html.erb
<%= link_to 'Add new message', new_message_path %>s
    <% @messages.each do |message| %>
      <ul>
        <li>
        Chat id: <%= message.chat_id   %><br>
        Receiver id:<%= message.user_id %><br>
        Body: <%= message.body%><br>
        Created at: <%= message.created_at %><br>
        Updated at: <%= message.updated_at %><br>
        <%= link_to 'Show', message_path(message) %>
        <%= link_to 'Edit', edit_message_path(message) %><br>
        </li>
      </ul>
    <% end %>

Whats_new/app/views/messages/new.html.erb
<h1>New Message</h1>
<%= render 'form', message: @message %>
<%= link_to 'Back', messages_path %>

Whats_new/app/views/messages/show.html.erb
<h1>Message Details</h1>

<p><strong>Chat id:</strong> <%= @message.chat_id  %></p>
<p><strong>User id:</strong> <%= @message.user_id%></p>
<p><strong>Body:</strong> <%= @message.body%></p>
<p><strong>Created at:</strong> <%= @message.created_at %></p>
<p><strong>Updated at:</strong> <%= @message.updated_at %></p>
<%= link_to 'Back', messages_path %>
<%= link_to 'Edit', edit_message_path(@message) %>


<h2>User Details</h2>
<p><strong>ID:</strong> <%= @user.id %></p>
<p><strong>First name:</strong> <%= @user.first_name %></p>
<p><strong>Last Name:</strong> <%= @user.last_name %></p>
<p><strong>Email:</strong> <%= @user.email %></p>
<p><strong>Created at:</strong> <%= @user.created_at %></p>
<p><strong>Updated at:</strong> <%= @user.updated_at %></p>

<h2>Chat Details</h2>
<p><strong>Users id:</strong> <%= @chat.sender_id %></p>
<p><strong>Receiver id:</strong> <%= @chat.receiver_id%></p>
<p><strong>Created at:</strong> <%= @chat.created_at %></p>
<p><strong>Updated at:</strong> <%= @chat.updated_at %></p>

Whats_new/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/users">Home <span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/users">Users</a>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <a class="nav-link" href="/chats">My Inbox</a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" href="/messages">All Messages</a>
      </li>

        <li class="nav-item">
          <%= button_to 'Cerrar sesión', destroy_user_session_path, method: :delete, data: { confirm: "¿Seguro que quieres salir?" }, class: "btn btn-link nav-link" %>

        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Iniciar sesión', new_user_session_path, class: "btn btn-primary" %>

        </li>
      <% end %>
    </ul>
  </div>
</nav>

Whats_new/app/views/users/_form.html.erb
<%= form_with model: @user, url: users_path, local: true do |form| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> Cant save the user:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name, "Nombre" %><br>
    <%= form.text_field :first_name, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :last_name, "Apellido" %><br>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email, "Correo electrónico" %><br>
    <%= form.email_field :email %>
  </div>
  <div class="field">
    <%= form.label :password, "Contraseña " %><br>
    <%= form.password_field :password %>
  </div>
  <div class="field">
    <%= form.label :password_confirmation, "Confirmar contraseña" %><br>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

Whats_new/app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'form', user: @user %>
<%= link_to 'Back', user_path(@user) %>

Whats_new/app/views/users/index.html.erb
<%= link_to 'Add new user', new_user_path %>   
    <% @users.each do |user| %>
      <ul>
        <li>
        Id: <%= user.id %><br>
        First name:<%= user.first_name %><br>
        Last name:<%= user.last_name%><br>
        Email:<%= user.email %><br>
        Created at: <%= user.created_at %><br>
        Updated at: <%= user.updated_at %><br>
        <%= link_to 'Show', user_path(user) %>
        <%= link_to 'Edit', edit_user_path(user) %><br>
        </li>
      </ul>
    <% end %>
    
    

Whats_new/app/views/users/new.html.erb
<div class="w3-container">
  <h1>Nuevo Usuario</h1>
  <%= render 'form', user: @user %>
  <%= link_to 'Back', users_path %>
</div>

Whats_new/app/views/users/show.html.erb
<h1>User Details</h1>

<p><strong>ID:</strong> <%= @user.id %></p>
<p><strong>First name:</strong> <%= @user.first_name %></p>
<p><strong>Last Name:</strong> <%= @user.last_name %></p>
<p><strong>Email:</strong> <%= @user.email %></p>
<p><strong>Created at:</strong> <%= @user.created_at %></p>
<p><strong>Updated at:</strong> <%= @user.updated_at %></p>

<%= link_to 'Back', users_path %>
<%= link_to 'Edit', edit_user_path(@user) %>

<h2>Chats where user participates</h2>
<%
  all_chats = @s_chats + @r_chats
%>
<% if all_chats.any? %>
  <ul>
    <% all_chats.each do |chat| %>
      <li>
        <%= link_to chat_path(chat) do %>
          Chat <%= chat.id %>: <%= chat.sender.id %> => <%= chat.receiver.id %>
        <% end %>

        <% user_msgs = @messages.select { |m| m.chat_id == chat.id }%>
        <% if user_msgs.any? %>
          <ul class="chat-messages">
            <% user_msgs.each do |msg| %>
              <li>
                <%= l(msg.created_at, format: :short) %> <%= msg.body %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p><em>No messages from this user in this chat.</em></p>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>This user don’t have any chat.</p>
<% end %>